### ISSUE TITLE
Fixing the issues with your Nav_Bar.

### ISSUE THREAD

**Issue by Juadebfm** [Taurus-Zeus/My-first-bootstrap-project#1]
1. Remove everything you currently have in the Nav section, including the section tag
2. Add the code below
    <nav class="navbar navbar-expand-lg navbar-light bg-light smallScreenFix">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >FX Rates <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Crypto Rates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Business News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Travel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sports</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">BD Conference</a>
          </li>
        </ul>
      </div>
    </nav>
    
    3. Go to your CSS and add the code below
    
    @media (max-width: 760px) {
  .smallScreenFix {
    display: flex;
    align-items: center;
    justify-content: end;
  }
}

Everything should be fine from there

**Comment by Juadebfm** [comment]
Also On your cards, i also changed the "<div class="card" style="width: 18rem;">" to "<div class="card" style="width: 100%;">" to make it look better
I also added "mb-3" to the first card and second"<div class="card mb-3" style="width: 100%;">"

I also removed the "height="120"" not usefull.

Instead add a height with normal css

**Comment by Taurus-Zeus** [comment]
thank you sir, i've done that now.
